Device: auto

DevicesList:
  - ToMemoryYourDevices
  - TheSecondDevices
  - AsStorageHistoryDevices

DataPath: source/data/

Who: Skii



Defult:
  ImportantRace: {'24': 24, '29': 29, '31': 31, '34': 34, '45': 45, '54': 54, '70': 70}
  ValidRace: {'22': 22, '32': 32, '41': 41, '42': 42, '49': 49, '51': 51, '53': 53, '57': 57, '59': 59, '65': 65, '66': 66, '71': 71}
  CommonRace: {}

  Speed:
    初始: 100
    第一年结束: 350
    第二年继承前: 400
    第二年夏季合宿前: 480
    第二年夏季合宿后: 550
    第二年结束: 600
    第三年继承前: 650
    第三年夏季合宿前: 700
    第三年夏季合宿后: 800
    全局: 900
    Exception: 900
  Stamina:
    初始: 100
    第一年结束: 250
    第二年继承前: 300
    第二年夏季合宿前: 400
    第二年夏季合宿后: 420
    第二年结束: 450
    第三年继承前: 480
    第三年夏季合宿前: 580
    第三年夏季合宿后: 620
    全局: 620
    Exception: 620
  Power:
    初始: 100
    第一年结束: 220
    第二年继承前: 250
    第二年夏季合宿前: 280
    第二年夏季合宿后: 300
    第二年结束: 320
    第三年继承前: 380
    第三年夏季合宿前: 420
    第三年夏季合宿后: 460
    全局: 500
    Exception: 500
  Will:
    限制: 200 
    全局: 200
  Intell:
    软目标: 400
    全局: 400



Skii:
  ImportantRace: {'24': 24, '29': 29, '31': 31, '34': 34, '45': 45, '54': 54, '70': 70}
  ValidRace: {'22': 22, '32': 32, '41': 41, '42': 42, '49': 49, '51': 51, '53': 53, '57': 57, '59': 59, '65': 65, '66': 66, '71': 71}
  CommonRace: {}

  Speed:
    初始: 100
    第一年结束: 300
    第二年继承前: 330
    第二年夏季合宿前: 400
    第二年夏季合宿后: 475
    第二年结束: 520
    第三年继承前: 580
    第三年夏季合宿前: 650
    第三年夏季合宿后: 700
    全局: 800
    Exception: 800
  Stamina:
    初始: 100
    第一年结束: 250
    第二年继承前: 320
    第二年夏季合宿前: 375
    第二年夏季合宿后: 450
    第二年结束: 500
    第三年继承前: 540
    第三年夏季合宿前: 580
    第三年夏季合宿后: 600
    全局: 620
    Exception: 620
  Power:
    初始: 100
    第一年结束: 250
    第二年继承前: 300
    第二年夏季合宿前: 360
    第二年夏季合宿后: 400
    第二年结束: 450
    第三年继承前: 500
    第三年夏季合宿前: 550
    第三年夏季合宿后: 600
    全局: 600
    Exception: 600
  Will:
    限制: 200 
    全局: 200
  Intell:
    软目标: 400
    全局: 400


Sky:
  ImportantRace: {'24': 24, '29': 29, '31': 31, '34': 34, '45': 45, '54': 54, '70': 70}
  ValidRace: {'22': 22, '32': 32, '41': 41, '42': 42, '49': 49, '51': 51, '53': 53, '57': 57, '59': 59, '65': 65, '66': 66, '71': 71}
  CommonRace: {}

  Speed:
    初始: 100
    第一年结束: 300
    第二年继承前: 360
    第二年夏季合宿前: 420
    第二年夏季合宿后: 500
    第二年结束: 550
    第三年继承前: 600
    第三年夏季合宿前: 650
    第三年夏季合宿后: 700
    全局: 800
    Exception: 800
  Stamina:
    初始: 100
    第一年结束: 250
    第二年继承前: 300
    第二年夏季合宿前: 375
    第二年夏季合宿后: 450
    第二年结束: 500
    第三年继承前: 520
    第三年夏季合宿前: 580
    第三年夏季合宿后: 600
    全局: 620
    Exception: 620
  Power:
    初始: 100
    第一年结束: 250
    第二年继承前: 300
    第二年夏季合宿前: 360
    第二年夏季合宿后: 400
    第二年结束: 450
    第三年继承前: 500
    第三年夏季合宿前: 550
    第三年夏季合宿后: 600
    全局: 600
    Exception: 600
  Will:
    限制: 200 
    全局: 200
  Intell:
    软目标: 400
    全局: 400
